#!/bin/bash

### 可配置项 ############################################
backendFolder='nestjs-template'
projects=("nestjs-template")

########################################################
basepath=`pwd`
. ./shell/func/reverseFn
. ./shell/func/baseFn
. ./shell/func/apiFn
case $1 in
'install')
installBasement
;;
'start')
execApiCommon 'start'
# startApi
# startReverse
;;
'stop')
execApiCommon 'stop'
# stopApi
# stopReverse
;;
esac
