#!/bin/bash

function execApiCommon {
    case $1 in
    'start')
    traverseProjects 'docker-compose up -d'
    ;;
    'stop')
    traverseProjects 'docker-compose stop'
    ;;
    'clear')
    traverseProjects 'docker-compose down'
    ;;
    'restart')
    traverseProjects 'docker-compose restart'
    ;;
    'recreate')
    traverseProjects 'docker-compose down && docker-compose up -d'
    ;;
    esac
}

function traverseProjects {
    for project in ${projects[@]}
    do
        echo $project
        cd $project && `$1` && cd $basepath
    done
}

# function installApi {
#     cd $backendFolder
# }

# function startApi {
#     cd $backendFolder && docker-compose up -d && cd $currentPath
# }

# function stopApi {
#     cd $backendFolder && docker-compose stop && cd $currentPath
# }

# function clearApi {
#     cd $backendFolder
# }