version: '3.7'

networks: 
    backend:
        name: allinpay-backend
        driver: bridge
    database:
        external: true
services: 
### NGINX Server #########################################
    nginx:
        image: "nginx:1.17.4"
        volumes:
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports: 
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            - backend
        container_name: allinpay-nginx
### MYSQL ################################################
    mysql:
        image: "registry.cn-hangzhou.aliyuncs.com/unintell/mysql:1.0.0"
        environment: 
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${MYSQL_TIMEZONE}
        volumes: 
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
            - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - backend
            - database
        container_name: allinpay-mysql
### Redis #################################################
    redis:
        image: "registry.cn-hangzhou.aliyuncs.com/unintell/redis:1.0.0"
        volumes: 
            - ${DATA_PATH_HOST}/redis:/data
        ports:
            - "${REDIS_PORT}:6379"
        networks: 
            - backend
        container_name: allinpay-redis
